-- Usuario/esquema propio del microservicio audit (no compartir con otros
-- microservicios: ver docker-compose de Javier, un usuario Oracle por servicio).

CREATE TABLE AUDIT_EVENT (
    ID              NUMBER(19)      NOT NULL,
    EVENT_ID        VARCHAR2(100)   NOT NULL,
    EVENT_TYPE      VARCHAR2(100)   NOT NULL,
    SOURCE_TOPIC    VARCHAR2(100)   NOT NULL,
    SHIPMENT_ID     VARCHAR2(100),
    ACTOR           VARCHAR2(150),
    OCCURRED_AT     TIMESTAMP       NOT NULL,
    TRACE_ID        VARCHAR2(100),
    CORRELATION_ID  VARCHAR2(100),
    RAW_PAYLOAD     CLOB,
    CONSTRAINT PK_AUDIT_EVENT PRIMARY KEY (ID),
    CONSTRAINT UQ_AUDIT_EVENT_ID UNIQUE (EVENT_ID)
);

CREATE SEQUENCE AUDIT_EVENT_SEQ START WITH 1 INCREMENT BY 50 NOCACHE;

-- Índices para los filtros de la pantalla de Auditoría (usuario, fecha, tipo de evento)
CREATE INDEX IX_AUDIT_EVENT_ACTOR ON AUDIT_EVENT (ACTOR);
CREATE INDEX IX_AUDIT_EVENT_TYPE ON AUDIT_EVENT (EVENT_TYPE);
CREATE INDEX IX_AUDIT_EVENT_OCCURRED_AT ON AUDIT_EVENT (OCCURRED_AT);
CREATE INDEX IX_AUDIT_EVENT_SHIPMENT_ID ON AUDIT_EVENT (SHIPMENT_ID);
